travis:
  secure:
    BINSTAR_TOKEN: LFmr1KNuwaNzHYyj3KoX3VQBJ4YsBFK/mLkyEbmtvOshmjaSyLNeda8eQG4hB+ZVJ1Gc8PpYWChzvCYDCUIh7bTHn1P3IWMXV5qkCT3mOCYC2LVBvp83L239BjEaEL3GRcdyn4ecabJt2xipJ9LnXeG27gJq6fmlPDrKjbFq4KKwcJwjyKbHZQTP6mTNtJGSs9PXSZf2s7IoC2kYPBGib2GaQ6j/6ZcbCXP/blfoy0I3HTrBSn+0A71PMK11aUzD7rAaxp8+5/2n5iRcuo1Mp0EkVx9WLUNI+9DGZvJnVv3vUx6QTozBo+tr5kU+enyhpvsGRXqTlk1nC51MdQChU6VgLtNhUUMdWU/mLG6qirHzPuil7vy5MWLZ7nZq2bkkwst6H4LR2H7AMTh8frfheBm0QBsl9vZRwOZOblHV5p/A8t/HGRUGqHID++hJAjT9KWT04OJik7kStjYe4od3G0kwHn98g5O/Y72qoR1I5IXpHMBJn/6vw/zhvvnJnqcIsI5Qc242A3mUoAZoVqEsLL1AkW43a+8Nr6k3pKpruYCPU3sfdvNddL2MVT59sc/XVZXB2wl8fIfpuydVdRQy6hID+ReZZ3fC9Dbde+cV+0JQ7/HE/Ie9J35HW7kSpDGousMQryroFnLipWkvpx4P2jjFMepYgqrK+FnPU2K1NTg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
