travis:
  secure:
    BINSTAR_TOKEN: OQLVTLHAcA45pF7u5wHkkMUIGu0vvp+iPB1t1xaNGmVssJ5FJ4ebH8jSW+o/SetIX5AW8Dapbrej5BWOvkoBFtxzpeg44clnn7BwLcRrbKNvUdKnUoDIWuqBDYDdXIzTBbYV3FqRQzI2X3isPAsrCYZFb1NIarXMiqkcDbK/mBNUxgUeI/YsIhXUR3Twz9mywpaWxOBi6vSpxLGSSNPk/obRcWceq3/Q7xSVxyn4ou/XYYznJHW8UPf5JYdnZ/EofFnYW/leU+FkHUdL8j79jRXs4iwOzJtzX6wIqST/5zmAYhkvcW1dylg7C392phY648AMpJvdSbb+kzIXCLyZDvoVF62yFKE+kM6RR6ErxJqusbs6eXBDHrLdtmoJmMh1PgtFJjxTFhv7/Bg4Y9megdvQ5trqij5NeiBJdmwEJDl5F50SgbzNx2XRwbmOqNMv21go99H4isIJoxxFHKhZkDPwd8PtcwR1sh7Zxb6RQWQL/OSTRJFhUodq6u7/WH2ddvJh4SkENrI6EZHoeYlhypPefcS2ahJarDODpRiC1GtD2KFTL9iYJDcHY6FfKl1T0+eJBhJKvSV+T/0Pi5k74noK5NE7bG9nNwOG+VmlqKJ7HLTJG/gaPYYU/ccDlSeml/Os/8ih5DLBgobgl7eR70uOfdHhWR6jv/NHERiyb/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
